TOPIC_MOVIES: movies.none.batch
TOPIC_RATINGS: ratings.none.batch

#REPLICATION_FACTOR: 2 # create topics before
STREAMS_THREADS: 2
COMPRESSION_TYPE: none
LINGER_MS: 10
BATCH_SIZE: 50000
FETCH_MIN_BYTES: 1
PROCESSING_GUARANTEE: at_least_once
